//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cz.fim.projekt;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import cz.fim.projekt.R.id;
import cz.fim.projekt.R.layout;

public final class ClientDetailActivity_
    extends ClientDetailActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.client_detail);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        gpsLat = ((TextView) findViewById(id.tvClientDetail_gpsLat));
        gpsLng = ((TextView) findViewById(id.tvClientDetail_gpsLng));
        name = ((TextView) findViewById(id.tvClientDetail_name));
        address = ((TextView) findViewById(id.tvClientDetail_address));
        phoneNumber = ((TextView) findViewById(id.tvClientDetail_phoneNumber));
        {
            View view = findViewById(id.btClientDetail_call);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ClientDetailActivity_.this.clickMakeCall();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btClientDetail_SignIn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ClientDetailActivity_.this.clickSignature();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btClientDetail_getGPS);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ClientDetailActivity_.this.clickGetGPS();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btClientDetail_Edit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ClientDetailActivity_.this.clickEdit();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btClientDetail_OK);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ClientDetailActivity_.this.clikOk();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ClientDetailActivity_.IntentBuilder_ intent(Context context) {
        return new ClientDetailActivity_.IntentBuilder_(context);
    }

    @Override
    public void setupDetail() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ClientDetailActivity_.super.setupDetail();
                } catch (RuntimeException e) {
                    Log.e("ClientDetailActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void clientUpdate() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ClientDetailActivity_.super.clientUpdate();
                } catch (RuntimeException e) {
                    Log.e("ClientDetailActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ClientDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ClientDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
